title: Simon
subtitle: 玄之又玄，众妙之门 # 一花一世界，一叶一菩提
description: Simon's blog # 主要用于SEO
keywords: Simon
author: Simon
language: zh-CN
timezone: Asia/Shanghai
url: https://blog.simon7.top/
permalink: :year:month:day/:post_title/

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: [README.md, readme.md,README.MD,模板.md,待办.md,hide]

new_post_name: :year-:i_month-:i_day-:title.md #title.md 
default_layout: post # 预设布局
auto_spacing: true # 中英文中间加空格 官网无此项
titlecase: true # 英文标题首字母是否大写
# 在新标签页中打开
external_link: 
  enable:  true
  field: post
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: true # 相对链接
future: false

highlight:
  enable: true 
  line_number: true
  auto_detect: true
  tab_replace: '    '
  wrap: true
  hljs: false

index2_include_index: false
index2_generator:
  - layout: 'index' # 使用现有索引布局
    path: '' # 输出到根目录: http://127.0.0.1:4000/
    index: true # 设置索引, results is_home() is true or not
    order_by: -date
    exclude:
      - tag hide
      - category hide 
	  
  - layout: 'index'
    path: 'myself'
    per_page: 10
    order_by: -date
    include: 
      - category hide
      - tag hide
	  
  - layout: 'archives'
    path: 'archives'
    exclude:
      - tag hide # 排除tag为hide的文章
      - category hide 

default_category: 未分类
meta_generator: true
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: 'date'
theme: next

deploy:
- type: git
  repo: git@github.com:nsleep/nsleep.github.io.git
  branch: master

# 网易云音乐 themes\next\layout\_macro\sidebar.swig
music:
  ID: 2067079376
  height: 90 # 32 | 90 | 430
