title: Simon 的博客
subtitle: 玄之又玄，众妙之门
description: 一花一世界，一叶一菩提
keywords: Simon
author: Simon
language: zh-CN
timezone: Asia/Shanghai


# ---------------------------------------------------------------
#:title-文件名称   
#:post_title-文章标题
#:id-文章 ID 不固定 #插件固定 hexo-abbrlink
#:category-分类
# 
#pretty_urls: 
## 改写 permalink 的值来美化 URL
## 是否在永久链接中保留尾部的 index.html，设置为 false 时去除
## 是否在永久链接中保留尾部的 .html, 设置为 false 时去除 (对尾部的 index.html无效)
# ---------------------------------------------------------------

url: https://blog.simon7.top/
root: /
permalink: :year:month:day/:post_title/
# 永久链接中各部分的默认值
permalink_defaults: 
#pretty_urls: 
#  trailing_index: 
#  trailing_html: 


# ---------------------------------------------------------------
# Directory 网址链接设置
# ---------------------------------------------------------------
#目录
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: [README.md, readme.md,README.MD,模板.md,待办.md,hide]

#文章
# 新文章的文件名
new_post_name: :year-:i_month-:i_day-:title.md #title.md 
default_layout: post # 预设布局
auto_spacing: false # 中英文中间加空格
titlecase: false # 英文标题首字母是否大写
# 在新标签页中打开
external_link: 
  enable:  true
  field: post # 对整个网站（site）或文章（post）生效
  exclude: ''
filename_case: 0 # 把文件名转换成大写(0)或小写(1)
render_drafts: false # 是否显示草稿
post_asset_folder: true # 是否启用Asset文件夹(给新文章一个单独的文件夹)
relative_link: false # 相对链接
future: false # 显示未来文章

# 代码块设置
highlight:
  enable: true 
  line_number: true # 显示行数
  auto_detect: true # 自动检测未指定语言的代码
  tab_replace: '    ' # 用 n 个空格替换 tabs
  wrap: true
  hljs: false
  

# ---------------------------------------------------------------
# 1.index2_generator
# 2.分类 & 标签
# 3.日期 / 时间格式
# 4.分页
# 参看: https://hexo.io/zh-cn/docs/configuration.html#分类-amp-标签
# ---------------------------------------------------------------

## Home page setting
## path: Root path for your blogs index page. (default = '')
## per_page: Posts displayed per page. (0 = disable pagination)
## order_by: Posts order. (Order by date descending by default)
#index_generator:
#  path: ''
#  per_page: 10
#  order_by: -date
#
# index2 generator是否包含官方的hexo-generator-index，默认true（包含）
# 参看: https://github.com/Jamling/hexo-generator-index2
index2_include_index: false
index2_generator:
  - layout: 'index' # 使用现有索引布局
    path: '' # 输出到根目录: http://127.0.0.1:4000/
    index: true # 设置索引, results is_home() is true or not
    order_by: -date
    exclude:
      - tag hide # 排除tag为hide的文章
      - category hide 
	  
  - layout: 'index' # 使用现有的存档布局
    path: 'myself' # 输出到Web文件夹: http://127.0.0.1:4000/myselfs/
    per_page: 10
    order_by: -date
    include: 
      - category hide # 包含category为Web的文章
      - tag hide # 排除tag为hide的文章
	  
  - layout: 'archives'
    path: 'archives'
    exclude:
      - tag hide # 排除tag为hide的文章
      - category hide 
      
# 分类 & 标签  #uncategorized
default_category: 未分类
category_map:  # 分类别名
tag_map:  # 标签别名

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time 格式
# 参看: http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
use_date_for_updat: true

# 分页
## 0以禁用分页
per_page: 10 # 每页文章量
pagination_dir: page # 分页目录

# 包含/排除文件
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore: 

# ---------------------------------------------------------------
# theme 主题
# ---------------------------------------------------------------

theme: next
theme_config:
  scheme: Gemini
  darkmode: true 
  site_state: false # Posts / Categories / Tags in sidebar.
  links:
    #Title: https://example.com
  post_edit:
    enable: true

# ---------------------------------------------------------------
# deploy 部署
# ---------------------------------------------------------------

deploy:
- type: git
  repo: git@github.com:nsleep/nsleep.github.io.git
  branch: master
#- type: heroku
#  repo: https://git.heroku.com/simon-iblog.git
#  messge: 
#- type: git
#  repo: git@e.coding.net:nsleep/nsleep.git
#  branch: master
#- type: git
#  repo: git@gitee.com:simon7/simon7.git
#  branch: master
#- type: ftpsync
#  host: 149.129.51.82
#  user: chengqian-hexoBlog
#  pass: SGkjBsr86f
#  remote: /www/wwwroot/chengqian-hexoBlog
#  port: 21




# ---------------------------------------------------------------
# search 搜索
# path - 文件的路径。默认是 search.xml。如果文件扩展名为 .json,则输出格式为JSON。
# field - 要搜索的搜索范围：
#   post (Default) -  仅涵盖您博客的所有帖子。
#   page - 仅涵盖您博客的所有页面。
#   all - 将涵盖您博客的所有帖子和页面。
# content - 是否包含每篇文章的全部内容。如果false，生成的结果仅覆盖没有主体的标题和其他元信息。默认是true。
# 排除索引 在文章顶部配置里加入 indexing: false 
# ---------------------------------------------------------------
#search:
#  path: search.xml 
#  field: post 
#  #content: true
#  format: html
#  limit: 1000

# hexo-admin authentification
# 参看：https://github.com/lwz7512/hexo-admin-ehc
#admin:
#  username: simon
#  password_hash: $2a$10$UbZsb8XJpR8FRXNwjvdiWuzgQCUbQwb6plW5KUB6/RGsA49MSCA2a
#  secret: tianxiecookies


# ---------------------------------------------------------------
# Yourself
# ---------------------------------------------------------------

# 网易云音乐 themes\next\layout\_macro\sidebar.swig
music:
  ID: 2067079376
  height: 90 # 32 | 90 | 430
